apiVersion: batch/v1
kind: Job
metadata:
  name: reactioncommerce-api-migrations-job
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: gcr.io/appliance-shack-cluster2/reaction-api-migrations:latest
        envFrom:
          - secretRef:
              name: reaction
      restartPolicy: Never
  backoffLimit: 4
  suspend: true
